import esbuild from "esbuild";
import builtins from "builtin-modules";

const isProduction = process.argv[2] === "production";
const isWatch = process.argv.includes("--watch");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
`;

const context = await esbuild.context({
  banner: {
    js: banner
  },
  bundle: true,
  entryPoints: ["src/main.ts"],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins
  ],
  format: "cjs",
  logLevel: "info",
  minify: isProduction,
  outfile: "main.js",
  platform: "browser",
  sourcemap: isProduction ? false : "inline",
  target: "es2022",
  treeShaking: true
});

if (isWatch) {
  await context.watch();
  console.log("Watching source files...");
} else {
  await context.rebuild();
  await context.dispose();
}
